// Koope catalog — 176 products, 30 categories. Generated data layer (v2.0).
// Each product: id = koope catalog #ID (searchable), seq = internal key for Supabase.
// Auto-synced from shop.koope.de — see scripts/sync-catalog.mjs.

window.KOOPE_UPDATED = '12.07.2026';

window.KOOPE_CATEGORIES = [
  { badge: 'getraenke', title: 'Drinks', ids: [1,2,3,4,5,6,7,8,9,10] },
  { badge: 'bier', title: 'Bier', ids: [11,12] },
  { badge: 'milch', title: 'Milk Alternatives', ids: [13,14,15] },
  { badge: 'kaffee', title: 'Coffee & Espresso', ids: [16,17,18] },
  { badge: 'tee', title: 'Tea', ids: [19,20,21,22,23,24] },
  { badge: 'nudeln', title: 'Pasta & Noodles', ids: [25,26,27,28,155,156,157] },
  { badge: 'getreide', title: 'Grains & Flour', ids: [29,30,31,32,33,34,35,36,37,38,152,162] },
  { badge: 'muesli', title: 'Muesli & Flakes', ids: [39,40,41] },
  { badge: 'reis', title: 'Rice & Legumes', ids: [42,43,44,45,46,47,48,49,50,163,164] },
  { badge: 'nuesse', title: 'Nuts & Seeds', ids: [51,52,53,54,55,56,57,58,59,60] },
  { badge: 'nussmus', title: 'Nut Butter', ids: [61,62,63,64,65,66,158] },
  { badge: 'aufstriche', title: 'Savory Spreads', ids: [67,68,69,70,71,72,73,74,75,159,160,161] },
  { badge: 'frucht', title: 'Fruit Spreads', ids: [76,77,78] },
  { badge: 'fertig', title: 'Ready Meals', ids: [79,80] },
  { badge: 'tofu', title: 'Tofu – Tofurei Leipzig', ids: [81,82,83,84] },
  { badge: 'konserven', title: 'Canned & Jarred Goods', ids: [85,86] },
  { badge: 'oele', title: 'Oils', ids: [87,88,89,90] },
  { badge: 'essig', title: 'Vinegar & Sauces', ids: [91,92,93,153,165,170] },
  { badge: 'salz', title: 'Salt & Sugar', ids: [94,95,96] },
  { badge: 'bruehe', title: 'Broth & Seasoning', ids: [97,154] },
  { badge: 'gewuerze', title: 'Spices', ids: [98,99,100,101,102,103,104,105,106] },
  { badge: 'kraeuter', title: 'Herbs', ids: [107,108,109,110,111,112] },
  { badge: 'trocken', title: 'Dried Fruit', ids: [113,114,115,116,117,118,119,120,169] },
  { badge: 'oliven', title: 'Oliven', ids: [121] },
  { badge: 'schoko', title: 'Chocolate & Sweets', ids: [122,123,124,125] },
  { badge: 'eis', title: 'Ice Cream & Sorbet', ids: [126,127,176] },
  { badge: 'koerperpflege', title: 'Personal Care & Soaps', ids: [128,129,130,131,132,133] },
  { badge: 'reinigung', title: 'Cleaning Products (Sonett)', ids: [134,135,136,137,138,139,140,141,142,143,144,166,167,168] },
  { badge: 'nonfood', title: 'Non-Food & Household', ids: [145,146,147,148,149,150,151,171] },
  { badge: 'neu', title: 'Neu / Unsortiert', ids: [172,173,174,175] },
];

window.KOOPE_PRODUCTS = [
  { seq: 1, id: '270', name: 'Rotkäppchen Sekt, alkoholfrei', detail: 'Flasche', unit: 'Fl', price: '4,84 €', cat: 'getraenke' },
  { seq: 2, id: '331', name: 'Natumi Haferdrink Natur', detail: '1 L', unit: 'Fl', price: '1,64 €', cat: 'getraenke', unavailable: true },
  { seq: 3, id: '267', name: 'Jolle Mate (Johannisbeere) – zickzack', detail: '0,5 L + 0,15 € Pfand', unit: 'Fl', price: '1,36 €', cat: 'getraenke', unavailable: true },
  { seq: 4, id: '266', name: 'KiLiMo (Sauerkirschlimo) – zickzack', detail: '0,5 L + 0,15 € Pfand', unit: 'Fl', price: '1,72 €', cat: 'getraenke' },
  { seq: 5, id: '268', name: 'Kolla Cola – zickzack', detail: '0,5 L + 0,15 € Pfand', unit: 'Fl', price: '1,72 €', cat: 'getraenke' },
  { seq: 6, id: '264', name: 'Kolle Mate – zickzack', detail: '0,5 L + 0,15 € Pfand', unit: 'Fl', price: '1,90 €', cat: 'getraenke' },
  { seq: 7, id: '263', name: 'Lipz Rhabarber', detail: '0,5 L + 0,15 € Pfand', unit: 'Fl', price: '2,15 €', cat: 'getraenke' },
  { seq: 8, id: '262', name: 'Lipz Schwarze Johannisbeere', detail: '0,5 L + 0,15 € Pfand', unit: 'Fl', price: '1,62 €', cat: 'getraenke' },
  { seq: 9, id: '261', name: 'Quipz (Quitte-Apfel-Schorle)', detail: '0,5 L + 0,15 € Pfand', unit: 'Fl', price: '2,27 €', cat: 'getraenke' },
  { seq: 10, id: '265', name: 'Zotrine (Zitronenlimonade) – zickzack', detail: '0,5 L + 0,15 € Pfand', unit: 'Fl', price: '1,36 €', cat: 'getraenke' },
  { seq: 11, id: '97', name: 'Fink Pils (Thüringen)', detail: '0,33 L + 0,08 € Pfand', unit: 'Fl', price: '1,29 €', cat: 'bier' },
  { seq: 12, id: '248', name: 'Fink, alkoholfrei (Thüringen)', detail: '0,33 L + 0,08 € Pfand', unit: 'Fl', price: '1,07 €', cat: 'bier' },
  { seq: 13, id: '137', name: 'Haferdrinkpulver (Blue Farm)', detail: 'ca. 1,37 € / L · nach Gewicht', unit: 'kg', price: '14,02 €/kg', cat: 'milch' },
  { seq: 14, id: '138', name: 'Haferdrinkpulver Barista (Blue Farm)', detail: 'ca. 1,58 € / L · nach Gewicht', unit: 'kg', price: '16,60 €/kg', cat: 'milch' },
  { seq: 15, id: '349', name: 'Kokosmilch-Pulver (Kamelur)', detail: 'nach Gewicht', unit: 'kg', price: '23,45 €/kg', cat: 'milch' },
  { seq: 16, id: '225', name: 'Kaffee, gesegelt (Café Chavalo, Nicaragua)', detail: 'nach Gewicht', unit: 'kg', price: '29,49 €/kg', cat: 'kaffee' },
  { seq: 17, id: '78', name: 'Espresso, gesegelt (Café Chavalo, Nicaragua)', detail: 'nach Gewicht', unit: 'kg', price: '29,49 €/kg', cat: 'kaffee' },
  { seq: 18, id: '156', name: 'Lupinenkaffee (DE–Hessen, 100 % Süßlupinen)', detail: 'nach Gewicht', unit: 'kg', price: '11,12 €/kg', cat: 'kaffee' },
  { seq: 19, id: '236', name: 'Abendtee (Karma Kollektiv)', detail: 'Lavendel, Lindenblüten, Kamille, Melisse …', unit: 'kg', price: '38,84 €/kg', cat: 'tee' },
  { seq: 20, id: '237', name: 'Basischer Kräutertee', detail: 'Brennnessel, Pfefferminze, Zitronengras', unit: 'kg', price: '24,72 €/kg', cat: 'tee' },
  { seq: 21, id: '238', name: 'Bergtee (Griechenland)', detail: 'nach Gewicht', unit: 'kg', price: '68,66 €/kg', cat: 'tee' },
  { seq: 22, id: '239', name: 'Fenchel-Anis-Kümmel', detail: 'nach Gewicht', unit: 'kg', price: '15,45 €/kg', cat: 'tee' },
  { seq: 23, id: '329', name: 'Ingwer-Zitrone', detail: 'nach Gewicht', unit: 'kg', price: '34,86 €/kg', cat: 'tee' },
  { seq: 24, id: '240', name: 'Morgentee', detail: 'Fenchel, Zitronengras, Grüner Tee, Mate …', unit: 'kg', price: '34,86 €/kg', cat: 'tee' },
  { seq: 25, id: '352', name: 'Farfalle (IT, Bio-Hartweizengriess)', detail: 'nach Gewicht', unit: 'kg', price: '3,43 €/kg', cat: 'nudeln', unavailable: true },
  { seq: 26, id: '342', name: 'Fusilli Dinkel hell (Alb Gold, DE)', detail: 'nach Gewicht', unit: 'kg', price: '5,23 €/kg', cat: 'nudeln', unavailable: true },
  { seq: 27, id: '354', name: 'Linguine (IT, Bio-Hartweizengriess)', detail: 'nach Gewicht', unit: 'kg', price: '3,43 €/kg', cat: 'nudeln' },
  { seq: 28, id: '353', name: 'Vollkorn Spirelli (IT)', detail: 'nach Gewicht', unit: 'kg', price: '3,33 €/kg', cat: 'nudeln', unavailable: true },
  { seq: 29, id: '347', name: 'Dinkel Vollkornmehl (Biohof Reiche, LK Leipzig, Bioland)', detail: 'nach Gewicht', unit: 'kg', price: '2,58 €/kg', cat: 'getreide' },
  { seq: 30, id: '161', name: 'Weizen Vollkornmehl (Maria Bienert, DE-Leipzig)', detail: 'nach Gewicht', unit: 'kg', price: '1,78 €/kg', cat: 'getreide' },
  { seq: 31, id: '57', name: 'Couscous, Vollkorn', detail: 'nach Gewicht', unit: 'kg', price: '3,97 €/kg', cat: 'getreide' },
  { seq: 32, id: '283', name: 'Buchweizen (Tarabao, Polen)', detail: 'nach Gewicht', unit: 'kg', price: '4,38 €/kg', cat: 'getreide' },
  { seq: 33, id: '113', name: 'Hirse (Maria Bienert, DE-Leipzig)', detail: 'nach Gewicht', unit: 'kg', price: '3,09 €/kg', cat: 'getreide' },
  { seq: 34, id: '363', name: 'Quinoa, Vollkorn (Mudda Natur, DE)', detail: 'nach Gewicht', unit: 'kg', price: '7,86 €/kg', cat: 'getreide' },
  { seq: 35, id: '187', name: 'Hafer, Korn – ganzes Korn (Maria Bienert, DE-Leipzig)', detail: 'nach Gewicht', unit: 'kg', price: '2,22 €/kg', cat: 'getreide' },
  { seq: 36, id: '62', name: 'Haferflocken, fein (Maria Bienert, DE-Leipzig)', detail: 'nach Gewicht', unit: 'kg', price: '2,19 €/kg', cat: 'getreide' },
  { seq: 37, id: '274', name: 'Polenta (B-Ware, −10 %)', detail: 'nach Gewicht', unit: 'kg', price: '2,56 €/kg', cat: 'getreide' },
  { seq: 38, id: '167', name: 'Hefeflocken (Kamelur)', detail: 'nach Gewicht', unit: 'kg', price: '33,60 €/kg', cat: 'getreide' },
  { seq: 39, id: '69', name: 'Müsli, 4-Kornflocken Bioland (Hafer, Gerste, Weizen, Roggen)', detail: 'nach Gewicht', unit: 'kg', price: '2,61 €/kg', cat: 'muesli' },
  { seq: 40, id: '310', name: 'Müsli, Schoko Crunchy (Müsli Mühle)', detail: 'nach Gewicht', unit: 'kg', price: '9,32 €/kg', cat: 'muesli' },
  { seq: 41, id: '338', name: 'Müsli, Paleo-Früchtemüsli (Tarabao)', detail: 'Buchweizenflocken, Erdmandel, Nüsse, Beeren', unit: 'kg', price: '11,12 €/kg', cat: 'muesli' },
  { seq: 42, id: '76', name: 'Langkornreis Thaibonnet, weiß (IT)', detail: 'nach Gewicht', unit: 'kg', price: '4,43 €/kg', cat: 'reis' },
  { seq: 43, id: '107', name: 'Weiße Bohnen (CN)', detail: 'nach Gewicht', unit: 'kg', price: '4,58 €/kg', cat: 'reis' },
  { seq: 44, id: '128', name: 'Schwarze Bohnen (Tarabao, AT)', detail: 'nach Gewicht', unit: 'kg', price: '6,63 €/kg', cat: 'reis' },
  { seq: 45, id: '37', name: 'Braune Linsen (IT)', detail: 'nach Gewicht', unit: 'kg', price: '3,17 €/kg', cat: 'reis' },
  { seq: 46, id: '136', name: 'Grüne Linsen, Du-Puy-Art (Tarabao, DE–Hessen)', detail: 'nach Gewicht', unit: 'kg', price: '5,50 €/kg', cat: 'reis' },
  { seq: 47, id: '155', name: 'Rote Linsen (Tarabao, TR)', detail: 'nach Gewicht', unit: 'kg', price: '4,38 €/kg', cat: 'reis' },
  { seq: 48, id: '116', name: 'Kichererbsen (Jonas Schulze Niehoff, DE–Sachsen-Anhalt)', detail: 'nach Gewicht', unit: 'kg', price: '3,87 €/kg', cat: 'reis' },
  { seq: 49, id: '175', name: 'Sojaschnetzel, grob (Sobo, DE/EU)', detail: 'nach Gewicht', unit: 'kg', price: '8,53 €/kg', cat: 'reis' },
  { seq: 50, id: '188', name: 'Leinsamen, braun (Tarabao, DE–Hessen)', detail: 'nach Gewicht', unit: 'kg', price: '5,50 €/kg', cat: 'reis' },
  { seq: 51, id: '63', name: 'Kürbiskerne (Biogewinner, AT)', detail: 'nach Gewicht', unit: 'kg', price: '11,56 €/kg', cat: 'nuesse' },
  { seq: 52, id: '173', name: 'Sesam, ungeschält (Uganda)', detail: 'nach Gewicht', unit: 'kg', price: '5,48 €/kg', cat: 'nuesse' },
  { seq: 53, id: '181', name: 'Sonnenblumenkerne (Riesernuss, DE–Bayern, Bioland)', detail: 'nach Gewicht', unit: 'kg', price: '3,77 €/kg', cat: 'nuesse' },
  { seq: 54, id: '180', name: 'Haselnusskerne (Riesernuss, Bayern)', detail: 'nach Gewicht', unit: 'kg', price: '20,31 €/kg', cat: 'nuesse' },
  { seq: 55, id: '133', name: 'Mandeln, ganz (Tarabao, Spanien)', detail: 'nach Gewicht', unit: 'kg', price: '15,06 €/kg', cat: 'nuesse' },
  { seq: 56, id: '355', name: 'Walnusskerne, Bruch (Riesernuss, Frankreich/Périgord)', detail: 'nach Gewicht', unit: 'kg', price: '14,51 €/kg', cat: 'nuesse' },
  { seq: 57, id: '134', name: 'Walnusskerne, B-Ware ⚠️ Bitte erhitzen! (Tarabao, Ungarn, −10 %)', detail: 'nach Gewicht', unit: 'kg', price: '13,04 €/kg', cat: 'nuesse' },
  { seq: 58, id: '154', name: 'Cashew, Bruch (Tarabao, Burkina Faso)', detail: 'nach Gewicht', unit: 'kg', price: '10,00 €/kg', cat: 'nuesse' },
  { seq: 59, id: '243', name: 'Cashews, Tamari-Sesam (Tarabao, Burkina Faso/Uganda)', detail: 'nach Gewicht', unit: 'kg', price: '20,11 €/kg', cat: 'nuesse' },
  { seq: 60, id: '242', name: 'Erdnüsse, gesalzen (Tarabao, Burkina Faso)', detail: 'nach Gewicht', unit: 'kg', price: '10,56 €/kg', cat: 'nuesse' },
  { seq: 61, id: '106', name: 'Erdnussmus Monki', detail: '650 g Glas', unit: 'Glas', price: '6,46 €', cat: 'nussmus' },
  { seq: 62, id: '70', name: 'Erdnussmus Terrasana, crunchy', detail: '500 g Glas', unit: 'Glas', price: '5,44 €', cat: 'nussmus' },
  { seq: 63, id: '252', name: 'Mandelmus braun, Terrasana', detail: '250 g Glas', unit: 'Glas', price: '4,98 €', cat: 'nussmus' },
  { seq: 64, id: '345', name: 'Mandelmus braun, Ecoterra', detail: '500 g Mehrwegglas + 0,15 € Pfand', unit: 'Glas', price: '9,82 €', cat: 'nussmus' },
  { seq: 65, id: '124', name: 'Tahin dark, Terrasana (Uganda)', detail: '500 g Glas', unit: 'Glas', price: '6,47 €', cat: 'nussmus' },
  { seq: 66, id: '366', name: 'Tahin weiß, Terrasana (Bolivien/Uganda)', detail: '500 g Glas', unit: 'Glas', price: '6,80 €', cat: 'nussmus' },
  { seq: 67, id: '351', name: 'Tofu küsst Wirsing (Leipspeis)', detail: '140 g Glas', unit: 'Glas', price: '2,81 €', cat: 'aufstriche' },
  { seq: 68, id: '226', name: 'Hummus, goldbäckener (Leipspeis)', detail: '140 g Glas', unit: 'Glas', price: '2,81 €', cat: 'aufstriche' },
  { seq: 69, id: '84', name: 'Grüne Linse & rote Tomate (Leipspeis)', detail: '140 g Glas', unit: 'Glas', price: '2,81 €', cat: 'aufstriche' },
  { seq: 70, id: '83', name: 'Purpurrote Königin – Rote Beete (Leipspeis)', detail: '140 g Glas', unit: 'Glas', price: '2,81 €', cat: 'aufstriche' },
  { seq: 71, id: '157', name: 'Sommertomate & Hanf (Leipspeis)', detail: '140 g Glas', unit: 'Glas', price: '2,81 €', cat: 'aufstriche' },
  { seq: 72, id: '86', name: 'Zucchini Lupini (Leipspeis)', detail: '140 g Glas', unit: 'Glas', price: '2,81 €', cat: 'aufstriche' },
  { seq: 73, id: '87', name: 'Confit Burgunder-Zwiebel (Leipspeis)', detail: '140 g Glas', unit: 'Glas', price: '3,37 €', cat: 'aufstriche' },
  { seq: 74, id: '88', name: 'Confit Riesling-Zwiebel (Leipspeis)', detail: '140 g Glas', unit: 'Glas', price: '3,37 €', cat: 'aufstriche' },
  { seq: 75, id: '246', name: 'Senf, süß & halbkörnig (Leipspeis)', detail: '150 ml Glas', unit: 'Glas', price: '2,81 €', cat: 'aufstriche' },
  { seq: 76, id: '371', name: 'Mirabelle, gelb (Rosenberg Delikatessen)', detail: '160 g Glas', unit: 'Glas', price: '3,54 €', cat: 'frucht' },
  { seq: 77, id: '370', name: 'Sanddorn (Rosenberg Delikatessen)', detail: '170 g Glas', unit: 'Glas', price: '3,54 €', cat: 'frucht' },
  { seq: 78, id: '372', name: 'Wilde Pflaume (Rosenberg Delikatessen)', detail: '160 g Glas', unit: 'Glas', price: '3,54 €', cat: 'frucht' },
  { seq: 79, id: '306', name: 'Linsenbolognese (Leipspeis)', detail: '500 g Pfandglas + 0,15 € Pfand', unit: 'Glas', price: '5,48 €', cat: 'fertig' },
  { seq: 80, id: '307', name: 'Veganes Gulasch (Leipspeis)', detail: '500 g Pfandglas + 0,15 € Pfand', unit: 'Glas', price: '5,48 €', cat: 'fertig' },
  { seq: 81, id: '153', name: 'Tofu geräuchert – Alge Soja', detail: 'ca. 200 g', unit: 'Stk', price: '3,37 €', cat: 'tofu' },
  { seq: 82, id: '150', name: 'Tofu geräuchert – Natur Soja', detail: 'ca. 200 g', unit: 'Stk', price: '3,37 €', cat: 'tofu' },
  { seq: 83, id: '152', name: 'Tofu geräuchert – Röstzwiebel Pfeffer', detail: 'ca. 200 g', unit: 'Stk', price: '3,37 €', cat: 'tofu' },
  { seq: 84, id: '177', name: 'Tofu geräuchert – Sesam-Soja', detail: 'ca. 200 g', unit: 'Stk', price: '3,37 €', cat: 'tofu' },
  { seq: 85, id: '344', name: 'Tomaten Passata (Ecoterra, IT)', detail: '500 g Mehrwegglas + 0,15 € Pfand', unit: 'Glas', price: '2,28 €', cat: 'konserven' },
  { seq: 86, id: '346', name: 'Tomatenmark (Ecoterra, IT)', detail: '270 g Mehrwegglas + 0,15 € Pfand', unit: 'Glas', price: '2,78 €', cat: 'konserven' },
  { seq: 87, id: '259', name: 'Bratöl Sonnenblumenkernöl (Teutoburger Ölmühle)', detail: '10 L · ca. 5,03 € / L · nach Gewicht', unit: 'kg', price: '5,46 €/kg', cat: 'oele' },
  { seq: 88, id: '193', name: 'Olivenöl (Griechenland, 5-L-Kanister)', detail: 'ca. 15,52 € / L · nach Gewicht', unit: 'kg', price: '17,98 €/kg', cat: 'oele' },
  { seq: 89, id: '361', name: 'Rapsöl (Ölmühle Leipzig)', detail: 'nach Gewicht', unit: 'kg', price: '7,61 €/kg', cat: 'oele' },
  { seq: 90, id: '184', name: 'Sonnenblumenöl (Ölmühle Leipzig)', detail: 'nach Gewicht', unit: 'kg', price: '7,94 €/kg', cat: 'oele' },
  { seq: 91, id: '254', name: 'Apfelessig (Beutelsbacher, DE, 10 L)', detail: 'ca. 3,56 € / L · nach Gewicht', unit: 'kg', price: '3,52 €/kg', cat: 'essig' },
  { seq: 92, id: '260', name: 'Balsamico di Modena (De Nigris, IT)', detail: 'ca. 6,30 € / L · nach Gewicht', unit: 'kg', price: '5,25 €/kg', cat: 'essig', unavailable: true },
  { seq: 93, id: '168', name: 'Sojasauce Shoyu (Arche Naturküche)', detail: 'ca. 11,14 € / L · nach Gewicht', unit: 'kg', price: '10,00 €/kg', cat: 'essig', unavailable: true },
  { seq: 94, id: '285', name: 'Steinsalz fein (Buxtrade, NL)', detail: 'nach Gewicht', unit: 'kg', price: '0,56 €/kg', cat: 'salz' },
  { seq: 95, id: '379', name: 'Steinsalz fein, ohne Zusätze (K+S, DE)', detail: 'nach Gewicht', unit: 'kg', price: '0,58 €/kg', cat: 'salz' },
  { seq: 96, id: '89', name: 'Rübenzucker (DE)', detail: 'nach Gewicht', unit: 'kg', price: '2,16 €/kg', cat: 'salz' },
  { seq: 97, id: '170', name: 'Gemüsebrühe, hefefrei vegan (Erntesegen)', detail: 'nach Gewicht', unit: 'kg', price: '10,70 €/kg', cat: 'bruehe', unavailable: true },
  { seq: 98, id: '314', name: 'Ingwer, gemahlen', detail: 'nach Gewicht', unit: 'kg', price: '11,46 €/kg', cat: 'gewuerze' },
  { seq: 99, id: '350', name: 'Kreuzkümmel (Cumin), gemahlen', detail: 'nach Gewicht', unit: 'kg', price: '43,70 €/kg', cat: 'gewuerze' },
  { seq: 100, id: '227', name: 'Curry Mild (Karma Kollektiv, IND/EGY)', detail: 'nach Gewicht', unit: 'kg', price: '34,83 €/kg', cat: 'gewuerze' },
  { seq: 101, id: '228', name: 'Kurkuma, gemahlen (Madagaskar)', detail: 'nach Gewicht', unit: 'kg', price: '23,64 €/kg', cat: 'gewuerze' },
  { seq: 102, id: '230', name: 'Muskatnuss, gemahlen (Indien)', detail: 'nach Gewicht', unit: 'kg', price: '62,22 €/kg', cat: 'gewuerze' },
  { seq: 103, id: '241', name: 'Paprika, geräuchert (Spanien)', detail: 'nach Gewicht', unit: 'kg', price: '34,45 €/kg', cat: 'gewuerze' },
  { seq: 104, id: '330', name: 'Paprikapulver, edelsüß (Spanien)', detail: 'nach Gewicht', unit: 'kg', price: '20,80 €/kg', cat: 'gewuerze' },
  { seq: 105, id: '233', name: 'Pfeffer, schwarz, ganz (Kambodscha)', detail: 'nach Gewicht', unit: 'kg', price: '22,75 €/kg', cat: 'gewuerze' },
  { seq: 106, id: '367', name: 'Zimt Ceylon (Madagaskar)', detail: 'nach Gewicht', unit: 'kg', price: '22,45 €/kg', cat: 'gewuerze' },
  { seq: 107, id: '368', name: 'Basilikum, getrocknet (Lüneburger Heide, DE)', detail: 'nach Gewicht', unit: 'kg', price: '39,24 €/kg', cat: 'kraeuter' },
  { seq: 108, id: '229', name: 'Kräuter der Provence', detail: 'nach Gewicht', unit: 'kg', price: '43,14 €/kg', cat: 'kraeuter' },
  { seq: 109, id: '231', name: 'Lorbeerblätter (Türkei)', detail: 'nach Gewicht', unit: 'kg', price: '67,41 €/kg', cat: 'kraeuter' },
  { seq: 110, id: '232', name: 'Oregano (Griechenland)', detail: 'nach Gewicht', unit: 'kg', price: '30,79 €/kg', cat: 'kraeuter' },
  { seq: 111, id: '234', name: 'Salatkräuter (DE/HU/CZ/NL)', detail: 'nach Gewicht', unit: 'kg', price: '38,65 €/kg', cat: 'kraeuter' },
  { seq: 112, id: '235', name: 'Thymian (Griechenland)', detail: 'nach Gewicht', unit: 'kg', price: '45,55 €/kg', cat: 'kraeuter' },
  { seq: 113, id: '337', name: 'Apfelchips (Tarabao, Polen)', detail: 'nach Gewicht', unit: 'kg', price: '22,36 €/kg', cat: 'trocken' },
  { seq: 114, id: '275', name: 'Aprikosen, ungeschwefelt (Türkei)', detail: 'nach Gewicht', unit: 'kg', price: '15,29 €/kg', cat: 'trocken' },
  { seq: 115, id: '43', name: 'Datteln Deglet Nour (Tunesien)', detail: 'nach Gewicht', unit: 'kg', price: '7,77 €/kg', cat: 'trocken' },
  { seq: 116, id: '159', name: 'Feigen (Messenien, GR)', detail: 'nach Gewicht', unit: 'kg', price: '12,36 €/kg', cat: 'trocken' },
  { seq: 117, id: '369', name: 'Heidelbeeren, gefriergetrocknet (Tarabao, Chile)', detail: 'nach Gewicht', unit: 'kg', price: '77,52 €/kg', cat: 'trocken' },
  { seq: 118, id: '162', name: 'Maulbeeren (Tarabao, Türkei)', detail: 'nach Gewicht', unit: 'kg', price: '14,49 €/kg', cat: 'trocken' },
  { seq: 119, id: '165', name: 'Pflaumen, entsteint (Tarabao, Bulgarien)', detail: 'nach Gewicht', unit: 'kg', price: '10,00 €/kg', cat: 'trocken' },
  { seq: 120, id: '55', name: 'Sultaninen (Türkei)', detail: 'nach Gewicht', unit: 'kg', price: '7,90 €/kg', cat: 'trocken' },
  { seq: 121, id: '160', name: 'Kalamon-Oliven (Messenien, GR)', detail: 'nach Gewicht', unit: 'kg', price: '14,98 €/kg', cat: 'oliven' },
  { seq: 122, id: '251', name: 'Choco Knuspies Dunkel – Kichererbsen (Hülsenreich)', detail: 'nach Gewicht', unit: 'kg', price: '22,47 €/kg', cat: 'schoko' },
  { seq: 123, id: '348', name: 'Kakaopulver (Nusskauf, Peru/DR)', detail: 'nach Gewicht', unit: 'kg', price: '24,14 €/kg', cat: 'schoko' },
  { seq: 124, id: '245', name: 'Schokolade, Himbeeren in Zartbitter (Tarabao, Ghana)', detail: 'nach Gewicht', unit: 'kg', price: '32,47 €/kg', cat: 'schoko' },
  { seq: 125, id: '244', name: 'Schokolade, Zartbitter Kakaosplitter 70% (Tarabao, Ghana)', detail: 'nach Gewicht', unit: 'kg', price: '22,36 €/kg', cat: 'schoko' },
  { seq: 126, id: '381', name: 'Sorbet Schwarze Johannisbeere (Quietzsch)', detail: '110 ml', unit: 'Stk', price: '2,25 €', cat: 'eis' },
  { seq: 127, id: '380', name: 'Sorbet Zitrone (Quietzsch, Sizilien)', detail: '110 ml', unit: 'Stk', price: '2,25 €', cat: 'eis' },
  { seq: 128, id: '139', name: 'Seife, Lavaerde Lavendel (KOJE, DE-Lpz)', detail: '50 g · palmöl- & plastikfrei', unit: 'Stk', price: '2,63 €', cat: 'koerperpflege' },
  { seq: 129, id: '91', name: 'Seife, Weiße Tonerde Brombeer + Lavendel (KOJE)', detail: '50 g', unit: 'Stk', price: '2,63 €', cat: 'koerperpflege' },
  { seq: 130, id: '90', name: 'Seife, Soleseife Mohn & Rose (KOJE)', detail: '50 g', unit: 'Stk', price: '2,63 €', cat: 'koerperpflege' },
  { seq: 131, id: '81', name: 'Seife, Soleseife Thymian + Limone (KOJE)', detail: '50 g', unit: 'Stk', price: '2,63 €', cat: 'koerperpflege' },
  { seq: 132, id: '182', name: 'Seife, Wolkensteiner Thermalwasser (KOJE)', detail: '50 g', unit: 'Stk', price: '2,63 €', cat: 'koerperpflege' },
  { seq: 133, id: '284', name: 'Schneestern Seife Körper & Hände (KOJE)', detail: '90 g', unit: 'Stk', price: '4,75 €', cat: 'koerperpflege', unavailable: true },
  { seq: 134, id: '143', name: 'Allesreiniger', detail: 'nach Gewicht', unit: 'kg', price: '2,85 €/kg', cat: 'reinigung' },
  { seq: 135, id: '35', name: 'Geschirrspülmittel', detail: 'nach Gewicht', unit: 'kg', price: '2,71 €/kg', cat: 'reinigung' },
  { seq: 136, id: '144', name: 'Glasreiniger', detail: 'nach Gewicht', unit: 'kg', price: '2,44 €/kg', cat: 'reinigung' },
  { seq: 137, id: '365', name: 'Handseife Citrus', detail: 'nach Gewicht', unit: 'kg', price: '6,20 €/kg', cat: 'reinigung' },
  { seq: 138, id: '41', name: 'Handseife Rosmarin', detail: 'nach Gewicht', unit: 'kg', price: '6,39 €/kg', cat: 'reinigung' },
  { seq: 139, id: '36', name: 'Maschinenspülmittel', detail: 'nach Gewicht', unit: 'kg', price: '3,65 €/kg', cat: 'reinigung' },
  { seq: 140, id: '77', name: 'Waschmittel flüssig, Lavendel', detail: 'nach Gewicht', unit: 'kg', price: '2,70 €/kg', cat: 'reinigung' },
  { seq: 141, id: '253', name: 'Waschmittel Olive (Wolle & Seide)', detail: 'nach Gewicht', unit: 'kg', price: '4,24 €/kg', cat: 'reinigung' },
  { seq: 142, id: '33', name: 'Waschmittel Pulver', detail: 'nach Gewicht', unit: 'kg', price: '3,69 €/kg', cat: 'reinigung' },
  { seq: 143, id: '34', name: 'WC-Reiniger Zeder-Citronella', detail: 'nach Gewicht', unit: 'kg', price: '3,54 €/kg', cat: 'reinigung' },
  { seq: 144, id: '277', name: 'Waschsoda', detail: 'nach Gewicht', unit: 'kg', price: '0,49 €/kg', cat: 'reinigung' },
  { seq: 145, id: '93', name: 'Klopapier (Goldeimer, 100 % Recycling)', detail: '8 Rollen · Blauer Engel', unit: 'Pack', price: '4,68 €', cat: 'nonfood' },
  { seq: 146, id: '357', name: 'Stumpenkerze bunt (Biokema, Thüringen)', detail: '60×55 mm', unit: 'Stk', price: '2,14 €', cat: 'nonfood' },
  { seq: 147, id: '358', name: 'Stumpenkerze weiß (Biokema, Thüringen)', detail: '60×120 mm', unit: 'Stk', price: '2,97 €', cat: 'nonfood' },
  { seq: 148, id: '360', name: 'Stabkerze bunt (Lichtbringer, Sachsen-Anhalt, Rapswachs)', detail: '2×20,5 cm', unit: 'Stk', price: '1,85 €', cat: 'nonfood' },
  { seq: 149, id: '359', name: 'Stabkerze naturweiß (Lichtbringer, Sachsen-Anhalt, Rapswachs)', detail: '2×20,5 cm', unit: 'Stk', price: '1,72 €', cat: 'nonfood' },
  { seq: 150, id: '356', name: 'Teelichte (Biokema, Thüringen)', detail: 'pro Stück', unit: 'Stk', price: '0,11 €', cat: 'nonfood' },
  { seq: 151, id: '362', name: 'Teelichtglas (Biokema)', detail: 'pro Stück', unit: 'Stk', price: '0,86 €', cat: 'nonfood' },
  { seq: 152, id: '375', name: 'Backpulver (DE)', detail: 'ca. 1 kg', unit: 'kg', price: '11,14 €/kg', cat: 'getreide', isNew: true },
  { seq: 153, id: '174', name: 'Essig, Apfelessig, naturtrüb (Voelkel, DE)', detail: 'ca. 1 kg', unit: 'kg', price: '2,94 €/kg', cat: 'essig', isNew: true },
  { seq: 154, id: '44', name: 'Gemüsebrühe, hefefrei (Erntesegen, CH)', detail: 'ca. 1 kg', unit: 'kg', price: '10,70 €/kg', cat: 'bruehe', isNew: true },
  { seq: 155, id: '74', name: 'Nudeln, Farfalle semola klein (IT)', detail: '1 kg, ca. 1 kg', unit: 'kg', price: '3,12 €/kg', cat: 'nudeln', isNew: true },
  { seq: 156, id: '51', name: 'Nudeln, Spaghetti (IT)', detail: '1 kg, ca. 1 kg', unit: 'kg', price: '3,02 €/kg', cat: 'nudeln', isNew: true },
  { seq: 157, id: '75', name: 'Nudeln, Spirelli Vollkorn (IT)', detail: '1 kg, ca. 1 kg', unit: 'kg', price: '3,02 €/kg', cat: 'nudeln', isNew: true },
  { seq: 158, id: '373', name: 'Nussmus, Monki-Tahin (NL / BO/UG)', detail: '650 g', unit: '650 g', price: '8,11 €', cat: 'nussmus', isNew: true },
  { seq: 159, id: '276', name: 'Pesto Olive (bioverde, DE)', detail: '125 ml', unit: '125 ml', price: '2,90 €', cat: 'aufstriche', isNew: true },
  { seq: 160, id: '376', name: 'Pesto rosso (La Selva, IT)', detail: '130 g', unit: '130 g', price: '2,52 €', cat: 'aufstriche', isNew: true },
  { seq: 161, id: '377', name: 'Pesto Verde (Terra Sana, IT)', detail: '180 g', unit: '180 g', price: '4,90 €', cat: 'aufstriche', isNew: true },
  { seq: 162, id: '172', name: 'Polenta (DE)', detail: 'ca. 1 kg', unit: 'kg', price: '2,95 €/kg', cat: 'getreide', isNew: true },
  { seq: 163, id: '61', name: 'Reis, Basmati, weiß (PK)', detail: 'ca. 1 kg', unit: 'kg', price: '3,83 €/kg', cat: 'reis', isNew: true },
  { seq: 164, id: '374', name: 'Reis, Milchreis, rund, weiß (IT)', detail: 'ca. 1 kg', unit: 'kg', price: '4,76 €/kg', cat: 'reis', isNew: true },
  { seq: 165, id: '378', name: 'Shoyu (Sojasauce) (NL)', detail: 'ca. 1 kg', unit: 'kg', price: '9,37 €/kg', cat: 'essig', isNew: true },
  { seq: 166, id: '384', name: 'Sonett Badreiniger (DE)', detail: '10 L, ca. 1 kg', unit: 'kg', price: '2,36 €/kg', cat: 'reinigung', isNew: true },
  { seq: 167, id: '383', name: 'Sonett Scheuerschwamm (DE)', detail: '2er-Pack', unit: '2er-Pack', price: '2,32 €', cat: 'reinigung', isNew: true },
  { seq: 168, id: '382', name: 'Sonett Spülschwamm (DE)', detail: '2er-Pack', unit: '2er-Pack', price: '2,32 €', cat: 'reinigung', isNew: true },
  { seq: 169, id: '385', name: 'Trockenobst, Datteln, Deglet Nour (TUN)', detail: 'ca. 1 kg', unit: 'kg', price: '7,57 €/kg', cat: 'trocken', isNew: true },
  { seq: 170, id: '386', name: 'Essig, Balsamico di Modena (De Nigris, IT)', detail: 'ca. 1 kg', unit: 'kg', price: '5,25 €/kg', cat: 'essig', isNew: true },
  { seq: 171, id: '387', name: 'Non-Food, Denttabs Zahnputztabletten, Minze, mit Fluorid (DE)', detail: 'ca. 0,1 kg', unit: 'kg', price: '10,50 €/kg', cat: 'nonfood', isNew: true },
  { seq: 172, id: '197', name: 'Tempeh | Lupine | Natur', detail: '200 g', unit: '200 g', price: '3,37 €', cat: 'neu', isNew: true },
  { seq: 173, id: '209', name: 'Tempeh | Lupine | natur [tiefgekühlt]', detail: '500 g', unit: '500 g', price: '6,52 €', cat: 'neu', isNew: true },
  { seq: 174, id: '198', name: 'Tempeh | Lupine | Vurst', detail: '220 g', unit: '220 g', price: '4,16 €', cat: 'neu', isNew: true },
  { seq: 175, id: '199', name: 'Tempeh | Soja | geräuchert', detail: '190 g', unit: '190 g', price: '3,99 €', cat: 'neu', isNew: true },
  { seq: 176, id: '388', name: 'Eis vegan Haselnuss', detail: '160 g', unit: '160 g', price: '2,07 €', cat: 'eis', isNew: true },
];
